Allow first-match module name matching
dergraaf/library-builder pull request #27
Opened 2018-05-25 20:57 UTC by salkinium

This adds the ability to query whether modules with a certain prefix exist: `env.has_module("repo:name*")`.
The implementation of `ModuleNameResolver` just returns the first match if any.

cc @dergraaf

2018-05-25 21:01 UTC, salkinium commented
[Example](https://github.com/modm-io/modm/commit/65c64545f2608387e39f0b4adcaccd67bebf4ee5#diff-a885160f894446aa364d392ee7905bedR95):

```py
def build(env):
    if not (env.has_module(":board.nucleo-*") or env.has_module(":board.al-avr*")):
        env.log.warn("GPIO test has been hardcoded to a Nucleo-64 board. "
                     "When porting make sure this test does not damage your board!")
        return
```

2018-05-28 21:23 UTC, dergraaf commented
Sounds reasonable. Would it make sense to implement a more general wildcard scheme?

2018-05-28 21:28 UTC, dergraaf requested changes

2018-05-28 21:28 UTC, dergraaf commented on lbuild/module.py
> +            find_first = (key[-1] == '*')
This is not used, but should probably used to enable the following lines

2018-05-28 21:28 UTC, dergraaf commented on lbuild/module.py
> +                if len(keys): key = keys[0];
Please don't use this style. There is (almost) no need for semicolons in python :smile:

2018-05-28 21:35 UTC, salkinium commented
Yeah, this was more of a quick hack, I wanted to start a discussion.

>  Would it make sense to implement a more general wildcard scheme?

Yes, absolutely! I was thinking something with a glob-like syntax, since we already have `:**` "any module" match. So something like `**:board.*` would collect *any* modules with a `board.` prefix.

2018-09-01 13:22 UTC, closed without merging